In [18]:
import pandas as pd
import os

pd.options.display.float_format = "{:.5f}".format

unlisted_directory = "../1.데이터셋/재무비율/외감재무비율"
os.listdir(unlisted_directory)

['외감_재무비율_rev_8.csv',
 '외감_재무비율_rev_9.csv',
 '외감_재무비율_rev_11.csv',
 '외감_재무비율_rev_10.csv',
 '외감_재무비율_rev_2.csv',
 '외감_재무비율_rev_3.csv',
 '외감_재무비율_rev_1.csv',
 '외감_재무비율_rev_4.csv',
 '외감_재무비율_rev_5.csv',
 '외감_재무비율_rev_7.csv',
 '외감_재무비율_rev_6.csv']

In [19]:
result = pd.DataFrame()

for filename in os.listdir(unlisted_directory):
    df = pd.read_csv(f"../1.데이터셋/재무비율/외감재무비율/{filename}", encoding="cp949")
    result = pd.concat([result, df])
print(result)

           회사명   거래소코드     회계년도    총자본증가율   유동자산증가율  비유동자산증가율    매출액증가율  \
0       주식회사성환   81567  2016/12   0.00000   0.00000   0.00000   0.00000
1       주식회사성환   81567  2017/12   0.42000  51.26000   0.16000  47.58000
2       주식회사성환   81567  2018/12   0.14000  29.22000  -0.09000   1.84000
3       주식회사성환   81567  2019/12   0.22000   5.53000   0.16000   5.59000
4       주식회사성회  102319  2021/12   0.00000   0.00000   0.00000   0.00000
...        ...     ...      ...       ...       ...       ...       ...
22147  주식회사나노팜   29937  2013/12 -16.05000 -26.14000   0.95000 -39.55000
22148  주식회사나노팜   29937  2014/12  -2.51000   8.45000 -16.03000 -51.91000
22149  주식회사나노팜   29937  2015/12  -1.80000  -6.83000   6.21000  -5.07000
22150  주식회사나노팜   29937  2018/12   0.00000   0.00000   0.00000   0.00000
22151  주식회사나노팜   29937  2019/12   5.09000  -0.22000  15.86000   0.79000

       자기자본증가율    순이익증가율  유형자산증가율  ...     매출액순이익률  매출액총이익률  총자본사업이익률  \
0      0.00000   0.00000  0.00000  ...    16.22000  0.00000   0.65000
1      0.37000 -19.46000 -0.01000  ...     8.85000  0.00000   0.18000
2      0.77000  23.43000 -0.09000  ...    10.73000  0.00000   0.25000
3      0.39000 -13.91000 -0.12000  ...     8.75000  0.00000   0.19000
4      0.00000   0.00000  0.00000  ... -7069.13000  0.00000  -3.41000
...        ...       ...      ...  ...         ...      ...       ...
22147 31.56000   9.26000 -8.97000  ...    14.93000 29.70000  22.90000
22148  0.81000 -83.09000 -9.05000  ...     5.25000 39.03000   5.53000
22149  0.49000 -88.05000 -3.21000  ...     0.66000 37.17000   1.41000
22150  0.00000   0.00000  0.00000  ...     0.88000 42.57000   3.28000
22151  2.73000 764.12000  9.48000  ...     7.53000 42.68000   5.59000

       총자본영업이익률  자기자본영업이익률    매출액영업이익률    금융비용부담률         설립일         상장일  \
0       0.65000    0.71000    12.51000    2.66000  2016/07/13           0
1       0.18000    0.19000     4.57000    3.64000  2016/07/13           0
2       0.25000    0.28000     6.47000    3.60000  2016/07/13           0
3       0.18000    0.20000     4.48000    3.12000  2016/07/13           0
4      -3.69000    0.00000 -4134.70000 2611.19000  2021/01/04           0
...         ...        ...         ...        ...         ...         ...
22147  21.92000   33.40000    18.15000   -0.82000  1998/08/06  0000/00/00
22148   4.66000    5.61000     7.24000   -1.23000  1998/08/06  0000/00/00
22149   0.75000    0.88000     1.20000   -0.99000  1998/08/06  0000/00/00
22150   2.95000    3.71000     4.62000   -0.50000  1998/08/06  0000/00/00
22151   5.14000    6.54000     8.19000   -0.71000  1998/08/06  0000/00/00

            상장폐지일
0               0
1               0
2               0
3               0
4               0
...           ...
22147  0000/00/00
22148  0000/00/00
22149  0000/00/00
22150  0000/00/00
22151  0000/00/00

[243684 rows x 62 columns]

In [20]:
result["회계년도"] = pd.to_datetime(result["회계년도"])
result = result[result["회계년도"].dt.month == 12].reset_index(drop=True)
result["회계년도"] = result["회계년도"].dt.year

/var/folders/y7/kjtd2q_j0c13ld5lwg5kd25r0000gn/T/ipykernel_59560/1217803801.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  result["회계년도"] = pd.to_datetime(result["회계년도"])

In [21]:
result

,회사명,거래소코드,회계년도,총자본증가율,유동자산증가율,비유동자산증가율,매출액증가율,자기자본증가율,순이익증가율,유형자산증가율,...,매출액순이익률,매출액총이익률,총자본사업이익률,총자본영업이익률,자기자본영업이익률,매출액영업이익률,금융비용부담률,설립일,상장일,상장폐지일
0,주식회사성환,81567,2016,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,16.22000,0.00000,0.65000,0.65000,0.71000,12.51000,2.66000,2016/07/13,0,0
1,주식회사성환,81567,2017,0.42000,51.26000,0.16000,47.58000,0.37000,-19.46000,-0.01000,...,8.85000,0.00000,0.18000,0.18000,0.19000,4.57000,3.64000,2016/07/13,0,0
2,주식회사성환,81567,2018,0.14000,29.22000,-0.09000,1.84000,0.77000,23.43000,-0.09000,...,10.73000,0.00000,0.25000,0.25000,0.28000,6.47000,3.60000,2016/07/13,0,0
3,주식회사성환,81567,2019,0.22000,5.53000,0.16000,5.59000,0.39000,-13.91000,-0.12000,...,8.75000,0.00000,0.19000,0.18000,0.20000,4.48000,3.12000,2016/07/13,0,0
4,주식회사성회,102319,2021,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,-7069.13000,0.00000,-3.41000,-3.69000,0.00000,-4134.70000,2611.19000,2021/01/04,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243022,주식회사나노팜,29937,2013,-16.05000,-26.14000,0.95000,-39.55000,31.56000,9.26000,-8.97000,...,14.93000,29.70000,22.90000,21.92000,33.40000,18.15000,-0.82000,1998/08/06,0000/00/00,0000/00/00
243023,주식회사나노팜,29937,2014,-2.51000,8.45000,-16.03000,-51.91000,0.81000,-83.09000,-9.05000,...,5.25000,39.03000,5.53000,4.66000,5.61000,7.24000,-1.23000,1998/08/06,0000/00/00,0000/00/00
243024,주식회사나노팜,29937,2015,-1.80000,-6.83000,6.21000,-5.07000,0.49000,-88.05000,-3.21000,...,0.66000,37.17000,1.41000,0.75000,0.88000,1.20000,-0.99000,1998/08/06,0000/00/00,0000/00/00
243025,주식회사나노팜,29937,2018,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.88000,42.57000,3.28000,2.95000,3.71000,4.62000,-0.50000,1998/08/06,0000/00/00,0000/00/00
243026,주식회사나노팜,29937,2019,5.09000,-0.22000,15.86000,0.79000,2.73000,764.12000,9.48000,...,7.53000,42.68000,5.59000,5.14000,6.54000,8.19000,-0.71000,1998/08/06,0000/00/00,0000/00/00

In [22]:
result.to_csv('../1.데이터셋/재무비율/외감_재무비율_final.csv', index=False)